# Generated by Django 3.1.2 on 2020-11-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='uname',
            new_name='Username',
        ),
    ]
