# Generated by Django 3.1.2 on 2020-11-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20201102_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Username',
            new_name='Uname',
        ),
    ]
