# Generated by Django 3.1.3 on 2020-11-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20201102_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='Uname',
            field=models.CharField(max_length=50),
        ),
    ]
