# Generated by Django 3.1.3 on 2020-11-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_auto_20201107_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Email',
            new_name='email',
        ),
    ]
