# Generated by Django 3.1.3 on 2020-11-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20201107_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
        migrations.AddField(
            model_name='signup',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
