# Generated by Django 3.1.3 on 2020-11-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20201107_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(default='email', max_length=254),
        ),
    ]
